# Generated by Django 2.2.3 on 2019-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20191229_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
