# Generated by Django 2.2.3 on 2019-12-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_auto_20191229_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
