# Generated by Django 2.2.3 on 2019-12-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_auto_20191229_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='kembali',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
