# Generated by Django 2.2.3 on 2019-12-25 12:34

import django.core.validators
from django.db import migrations, models
import kunjungan.models


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='angkatan',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), kunjungan.models.max_value_current_year], verbose_name='angkatan'),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='keterangan',
            field=models.TextField(verbose_name='keterangan'),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='nama',
            field=models.CharField(max_length=35, verbose_name='nama'),
        ),
    ]
