# Generated by Django 2.2.3 on 2019-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0002_auto_20191225_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='angkatan',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], verbose_name='angkatan'),
        ),
    ]
