# Generated by Django 2.2.3 on 2019-12-28 09:44

import django.core.validators
from django.db import migrations, models
import kunjungan.models


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0004_auto_20191225_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='angkatan',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), kunjungan.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='keterangan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='nama',
            field=models.CharField(max_length=35),
        ),
    ]
